spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri:
          default-label: dev
      profile: default
  config:
    activate:
      on-profile: dev
server:
  port: 9196
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: health